network:
  zmq_control_addr: tcp://*:60615
  # zmq_private_key: ${CUSTOM_EV_FOR_PRIVATE_KEY}
  zmq_info_addr: tcp://*:60625
  zmq_encoding: json
  zmq_publish_console: true
  redis_addr: ${REDIS_ADDR}
  redis_name_prefix: qs_default
startup:
  # keep_re: true
  startup_dir: /app/startup
  existing_plans_and_devices_path: /app/startup
  user_group_permissions_path: /app/startup
